#!/bin/bash -x

BASEDIR="/home/merengueproject"
PROJECTNAME="merengueprojectorg"
PROJECTDIR=$BASEDIR/$PROJECTNAME
PIDFILE="$BASEDIR/pid/$PROJECTNAME.pid"
VIRTUALENV=$BASEDIR/virtualenv/
SOCKET="$BASEDIR/sock/uwsgi.sock"
LOGFILE="$BASEDIR/logs/$PROJECTNAME.uwsgi.log"

export LC_ALL=es_ES.UTF-8

function start {
   echo "Iniciando Merengue:"
   cd $BASEDIR
   . $BASEDIR/virtualenv/bin/activate
   $BASEDIR/bin/uwsgi -p 2 -C -M 4 -A 4 -m -s $SOCKET -H $VIRTUALENV $PROJECTNAME.wsgi --pythonpath $PROJECTDIR/ --pidfile $PIDFILE -d $LOGFILE
}

function stop {
    echo "Terminando Merengue:"
    pgrep uwsgi |xargs kill -9
}

case "$1" in
    start)
        start
    ;;

    stop)
        stop
    ;;
    restart)
        stop
        start
    ;;
    *)
        echo "Usage: ~/scripts/merengue {start|stop|restart}"
        exit 1
    ;;
esac

exit 0

