#!/bin/bash -e

BASEDIR=/home/merengue
PROJECTDIR=$BASEDIR/merengueproject

function enable_virtualenv {
    echo "Activando el entorno (virtualenv)"
    cd $BASEDIR
    . virtualenv/bin/activate
}

function update_code {
    echo "Actualizando el proyecto a la ultima revision"
    cd $PROJECTDIR
    svn up --username=$SVNUSERNAME --password=$SVNPASSWORD
}
function remove_pyc_files {
    echo "Eliminando ficheros precompilados de python"
    find -iname "*.pyc" -exec rm {}  \;
}
function dmigrate {
    echo "Actualizando la base de datos"
    cd $PROJECTDIR
    python manage.py migrate
}

function sync_plugins_media {
    cd $PROJECTDIR
    python manage.py sync_plugins_media --all
}

function servers_restart {
    echo "Reiniciando los servidores"
    cd $BASEDIR
    . scripts/merengue restart
}

function sync_plugins_media {
    cd $PROJECTDIR/beta_merengue
    python manage.py sync_plugins_media --all
}

function update_doc {
    echo "Updating merengueproject documentacion"
    cd $BASEDIR/docs/
    svn up --username=$SVNUSERNAME --password=$SVNPASSWORD
    touch index.txt
    make html
}

enable_virtualenv
update_code
remove_pyc_files
dmigrate
servers_restart
