#!/bin/bash -e

BASEDIR=/home/merengueproject
MERENGUEDIR=$BASEDIR/merengueproject
PROJECTDIR=$MERENGUEDIR/beta_merengue

function enable_virtualenv {
    echo "Activando el entorno (virtualenv)"
    cd $BASEDIR
    . virtualenv/bin/activate
}

function update_code {
    echo "Actualizando el proyecto a la ultima revision"
    cd $MERENGUEDIR
    svn up --username=$SVNUSERNAME --password=$SVNPASSWORD
}
function remove_pyc_files {
    echo "Eliminando ficheros precompilados de python"
    find -iname "*.pyc" -exec rm {}  \;
}
function dmigrate {
    echo "Actualizando la base de datos"
    cd $PROJECTDIR
    python manage.py migrate
}
function servers_restart {
    echo "Reiniciando los servidores"
    cd $BASEDIR
    . scripts/nginxctl restart
    . scripts/portaluma restart
}

function update_doc {
    echo "Updating merengueproject documentacion"
    cd $BASEDIR/docs/
    touch index.txt
    make html
}

case "$1" in 
    project)
        enable_virtualenv
	update_code
	remove_pyc_files
	dmigrate
	servers_restart
    ;;
    documentation)
        enable_virtualenv
        update_doc
    ;;
    *)
        echo "Usage: ~/scripts/update {project|documentation}"
        exit 1
    ;;
esac

exit 0
